### ISSUE TITLE
1.0.2 errors on "invalid option: --server"

### ISSUE THREAD

**Issue by vandrijevik** [seattlerb/minitest-autotest#10]
Using the directions from [the documentation](http://docs.seattlerb.org/minitest-autotest/), I am trying to set up autotest for my minitest-based project:

```
$ cat .autotest
require "autotest/suffix"
require "autotest/bundler"
require "autotest/restart"

Autotest.add_hook :initialize do |at|
  at.testlib = ".minitest"
end
```

along with this `.minitest.rb`:

```
$ cat .minitest.rb 
gem "minitest"
require "minitest/autorun"
```

Starting `autotest` shows the following error message:

```
$ autotest
bundle exec /Users/vladimir/ruby/2.2.3/bin/ruby -I.:lib:test -rubygems -e "gem 'minitest'; %w[.minitest <SNIP-LOCAL-TEST-DIRECTORY-FILES>].each { |f| require f }" -- --server 46681

invalid option: --server

minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
```

Here are details about my local setup:

```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

$ gem -v
2.5.1

$ gem list | grep minitest
minitest (5.8.3, 5.4.3)
minitest-autotest (1.0.2)
minitest-server (1.0.3)
```

What am I doing wrong?

**Comment by vandrijevik** [comment]
Oh wow, I just figured this out. When using `minitest/bundler`, if the bundle does not include `minitest-server` (either by way of `minitest-autotest` or explicitly), `minitest` does not load the plugin, so `--server` is not recognized.

The solution was to add `minitest-autotest` to the `Gemfile` (in my case, by adding it to the `.gemspec` file), so that it can be on the load path when bundler sets it up, and so that minitest can load `minitest-server` as a plugin.

**Comment by zenspider** [comment]
Good catch! Glad you got yourself unstuck. Would you like to write up your experience into the README and send me a PR?
