### ISSUE TITLE
runs continually on failed test because log/test.log changed

### ISSUE THREAD

**Issue by krbullock** [seattlerb/minitest-autotest#17]
I'm running autotest on my current greenfield Rails 6.0 RC1 app. When I have a test failure, autotest re-runs the failed test constantly even though no further changes have been made to the files. Running with --debug seems to indicate that it's picking up the change to log/test.log:

```
Finished in 1.168905s, 32.5091 runs/s, 69.2956 assertions/s.
38 runs, 81 assertions, 0 failures, 1 errors, 0 skips
{:test_file_for=>["log/test.log", nil]}
{:test_file_for=>["log/test.log", nil]}
Files to test:
...
```

I'm at a loss to see why it's watching that file. This happens regardless of whether I `require 'autotest/rails'` in my .autotest config.

**Comment by zenspider** [comment]
1. Thank you for reporting.
2. You can just run with `autotest -v` to get the above output (and a lot more).
3. The "right" way to deal with this is to create a `.autotest` file and exclude that file or directory:

```ruby
Autotest.add_hook :initialize do |at|
  at.add_exception "log"
```

> I'm at a loss to see why it's watching that file.

Yeah. It bites me now and then as well. I wanted it to pick up things like Rakefile and anything else I might be messing with while running tests. Opt-in in the `.autotest` file might have been a wiser choice.

Lemme know if this addresses everything you brought or if I missed anything.

**Comment by krbullock** [comment]
@zenspider Thanks for the explanation, makes sense. I've added

```ruby
at.add_exception 'log'
at.add_exception 'coverage' # the other culprit in my project
```

to my project's .autotest and now it seems to be functioning correctly.
