### ISSUE TITLE
adding arbitrary rb files to watch

### ISSUE THREAD

**Issue by arifb** [seattlerb/minitest-autotest#18]
Hi, thanks for the project.

Am I missing something or is the conditions on which files autotest will run is hardcoded to only run tests in the `test` folder? (as well as the filename needing to be prefixed with `test_` but I do see the note in the README on working around that).

Am I able to arbitrarily add files to 'watch'?

Thanks.

**Comment by zenspider** [comment]
Please see:

1. https://github.com/seattlerb/minitest-autotest/blob/master/lib/autotest.rb#L37-L57 for general naming/strategy
2. https://github.com/seattlerb/minitest-autotest/blob/master/example_dot_autotest.rb for example config
3. https://github.com/seattlerb/minitest-autotest/blob/master/lib/autotest/rails.rb for example of alternative naming

**Comment by zenspider** [comment]
No response. Closing
