### ISSUE TITLE
red/green hooks missing

### ISSUE THREAD

**Issue by bhenderson** [seattlerb/minitest-autotest#4]
https://gist.github.com/bhenderson/676d423c1488d0fea4a9

not sure if this was intentional.

**Comment by zenspider** [comment]
It was intentional. I actually started with no hooks at all and have been slowly bringing them back as they prove their use. Feel free to throw me a PR.

**Comment by bhenderson** [comment]
I see now that the ran_command hook is sufficient. thanks

**Comment by bhenderson** [comment]
oh, fyi, green and red are still listed in the available hooks.
