### ISSUE TITLE
Autotest misbehaves if minitest/spec names have brackets in them

### ISSUE THREAD

**Issue by halostatue** [seattlerb/minitest-autotest#9]
* minitest-autotest crashes with an empty-char-class exception if the `describe` text or `it` text has empty brackets (e.g., `'#[]'`). 

```
Unhandled exception: empty char-class: /MIME::Types::#[]#(?-mix:test_0004_can\ be\ searched\ with\ the\ complete\ flag)/
```

* minitest-autotest fails to match if brackets are used elsewhere (e..g, `"some value [with brackets]"`) and not empty. It will try to match any one character matching the character class `[with brackes]`.

This feels like trusting the method names/class names for input, which is certainly true for minitest normal test case or method.

**Comment by zenspider** [comment]
Mmmmm... I don't remember fixing this, but I don't have a repro on it either.

No... looking at the release history, I've definitely not addressed this, but it doesn't appear to reproduce for me (still need to see if this was fixed over on minitest-server's side):

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I.:lib:test -rubygems -e '%w[test/test_minitest/test_spec.rb].each do |f| load f; end' -- --server 85029 -n '/(?:Array#(?:test_0003_should\ work\ even\ now\ \[\]|test_0002_should\ work\ \[even\ now\]))/'
Run options: --server 85029 -n "/(?:Array#(?:test_0003_should\\ work\\ even\\ now\\ \\[\\]|test_0002_should\\ work\\ \\[even\\ now\\]))/" --seed 31967

# Running:

:what?
F:what?
F

Finished in 0.003047s, 656.3833 runs/s, 656.3833 assertions/s.

  1) Failure:
Array#test_0002_should work [even now] [/Users/ryan/Work/p4/zss/src/minitest-autotest/dev/test/test_minitest/test_spec.rb:11]:
Epic Fail!


  2) Failure:
Array#test_0003_should work even now [] [/Users/ryan/Work/p4/zss/src/minitest-autotest/dev/test/test_minitest/test_spec.rb:17]:
Epic Fail!

2 runs, 2 assertions, 2 failures, 0 errors, 0 skips
```

**Comment by zenspider** [comment]
Nope. Can you provide code and/or env setup to reproduce this?

**Comment by halostatue** [comment]
I’ll have to look at it again; I have fallen out of the habit of using brackets in my tests, but I have noticed similarly weird issues with single quotes. I’ll see if I can work up a simple case for these issues.

**Comment by zenspider** [comment]
The single quote one is definitely fixed and released. Closing this for now. Feel free to reopen if you find a repro.

**Comment by halostatue** [comment]
Sounds good.
